---
apiVersion: v1
kind: Namespace
metadata:
  name: california-voters
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: california-voters
  name: californiavoters-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: californiavoters-app
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: californiavoters-app
    spec:
      containers:
      - image: jithmi97/registervotersapi:main
        imagePullPolicy: Always
        name: californiavoters-app
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  namespace: california-voters
  name: californiavoters-service
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: californiavoters-app
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: california-voters
  name: votersmanagement-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: votersmanagement-app
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: votersmanagement-app
    spec:
      containers:
      - image: jithmi97/votersmanagement:main
        imagePullPolicy: Always
        name: votersmanagement-app
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  namespace: california-voters
  name: votersmanagement-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: votersmanagement-app
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: california-voters
  name: votersmonitoring-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: votersmonitoring-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: votersmonitoring-app
    spec:
      containers:
      - image: jithmi97/votersmonitoring:main
        imagePullPolicy: Always
        name: votersmonitoring-app
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  namespace: california-voters
  name: votersmonitoring-service
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: votersmonitoring-app
  type: LoadBalancer
status:
  loadBalancer: {}